package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Administer generated by hbm2java
 */
@Entity
@Table(name = "Administer",
         schema = "dbo",
         catalog = "Russh"
)
public class Administer implements java.io.Serializable {

    @Id
    @Column(name = "Aid", unique = true, nullable = false)
    private String aid;
    @JoinColumn(name = "Auid", nullable = false)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Users users;

    public Administer() {
    }

    public Administer(String aid, Users users) {
        this.aid = aid;
        this.users = users;
    }

    public String getAid() {
        return this.aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

}
