package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Blockers generated by hbm2java
 */
@Entity
@Table(name="Blockers"
    ,schema="dbo"
    ,catalog="Russh"
)
public class Blockers  implements java.io.Serializable {


@Id
    @Column(name="Bid", unique=true, nullable=false)
     private String bid;
      @JoinColumn(name = "Buid", nullable = false)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
     private Users users;

    public Blockers() {
    }

    public Blockers(String bid, Users users) {
       this.bid = bid;
       this.users = users;
    }
   
    public String getBid() {
        return this.bid;
    }
    
    public void setBid(String bid) {
        this.bid = bid;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


