package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "Message",
        schema = "dbo",
        catalog = "Russh"
)
public class Message implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "generator", strategy = "native")
    @GeneratedValue(generator = "generator")
    @Column(name = "Mid", unique = true, nullable = false)
    private int mid;
    @JoinColumn(name = "MbeenUid")
    @ManyToOne(fetch = FetchType.EAGER)
    private Users beenuser;
    @JoinColumn(name = "Muid")
    @ManyToOne(fetch = FetchType.EAGER)
    private Users muser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Mdate", nullable = true, length = 23)
    private Date mdate;
    @Column(name = "Mdetail", nullable = false)
    private String mdetail;

    public Message() {
    }


    public Message(int mid, Users beenuser, Users muser, Date mdate, String mdetail) {
        this.mid = mid;
        this.beenuser = beenuser;
        this.muser = muser;
        this.mdate = mdate;
        this.mdetail = mdetail;
    }

    public int getMid() {
        return this.mid;
    }

    public void setMid(int mid) {
        this.mid = mid;
    }

    public Date getMdate() {
        return this.mdate;
    }

    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }

    public String getMdetail() {
        return this.mdetail;
    }

    public void setMdetail(String mdetail) {
        this.mdetail = mdetail;
    }

    public Users getBeenuser() {
        return beenuser;
    }

    public void setBeenuser(Users beenuser) {
        this.beenuser = beenuser;
    }

    public Users getMuser() {
        return muser;
    }

    public void setMuser(Users muser) {
        this.muser = muser;
    }

}
