package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Post generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "Post",
        schema = "dbo",
        catalog = "Russh"
)
public class Post implements java.io.Serializable {

    @Id
    @Column(name = "Pid", unique = true, nullable = false)
    private String pid;
    @Column(name = "Puser", unique = true, nullable = false)
    private String user;
    @Column(name = "Ptitle", nullable = false)
    private String ptitle;
    @Column(name = "Pabstr", nullable = false)
    private String pabstr;
    @Column(name = "Pdetails", nullable = false)
    private String pdetails;
    @Column(name = "Pblock", nullable = false)
    private String pblock;
    @Column(name = "Ppower", columnDefinition = "int default 0")
    private Integer Ppower;
    @Column(name = "Preadnum", columnDefinition = "int default 0")
    private Integer preadnum;

    public Post() {
    }

    public Post(String pid, String user, String ptitle, String pabstr, String pdetails, String pblock, Integer Ppower, Integer preadnum) {
        this.pid = pid;
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
        this.Ppower = Ppower;
        this.preadnum = preadnum;
    }

    public Post(String pid, String user, String ptitle, String pabstr, String pdetails, String pblock) {
        this.pid = pid;
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
    }

    

    public String getPid() {
        return this.pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }


    public String getPtitle() {
        return this.ptitle;
    }

    public void setPtitle(String ptitle) {
        this.ptitle = ptitle;
    }

    public String getPabstr() {
        return this.pabstr;
    }

    public void setPabstr(String pabstr) {
        this.pabstr = pabstr;
    }

    public String getPdetails() {
        return this.pdetails;
    }

    public void setPdetails(String pdetails) {
        this.pdetails = pdetails;
    }

    public String getPblock() {
        return this.pblock;
    }

    public void setPblock(String pblock) {
        this.pblock = pblock;
    }

    public Integer getPreadnum() {
        return this.preadnum;
    }

    public void setPreadnum(Integer preadnum) {
        this.preadnum = preadnum;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Integer getPpower() {
        return Ppower;
    }

    public void setPpower(Integer Ppower) {
        this.Ppower = Ppower;
    }

 
}
