package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.GenericGenerator;

/**
 * Post generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "Post",
        schema = "dbo",
        catalog = "Russh"
)
public class Post implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "generator", strategy = "native")
    @GeneratedValue(generator = "generator")
    @Column(name = "Pid", unique = true, nullable = false)
    private int pid;
    @JoinColumn(name = "Puser")
    @ManyToOne(fetch = FetchType.EAGER)
    private Users user;
    @Column(name = "Ptitle", nullable = false)
    private String ptitle;
    @Column(name = "Pabstr", nullable = false)
    private String pabstr;
    @Column(name = "Pdetails", nullable = false)
    private String pdetails;
    @Column(name = "Pblock", nullable = false)
    private String pblock;
    @Column(name = "Ppower", columnDefinition = "int default 0")
    private Integer Ppower;
    @Column(name = "Preadnum", columnDefinition = "int default 0")
    private Integer preadnum;
    @Column(name = "Ptime")
    @Temporal(TemporalType.TIMESTAMP)
    @Generated(GenerationTime.INSERT)
    private Date pdate;

    
    
    @OneToMany(mappedBy = "post", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
    private List<Reply> Replys;

    
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "Star",
            joinColumns = {
                @JoinColumn(name = "spid", referencedColumnName = "pid")},
            inverseJoinColumns = {
                @JoinColumn(name = "suid", referencedColumnName = "uid")})
    private List<Users> likedUsers;

    public Post() {
    }

    public Post(Users user, String ptitle, String pabstr, String pdetails, String pblock) {
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
    }

    
    
    public Post(int pid, Users user, String ptitle, String pabstr, String pdetails, String pblock, Integer Ppower, Integer preadnum) {
        this.pid = pid;
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
        this.Ppower = Ppower;
        this.preadnum = preadnum;
    }

    public Post(int pid, Users user, String ptitle, String pabstr, String pdetails, String pblock) {
        this.pid = pid;
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
    }

    public Post(int pid, Users user, String ptitle, String pabstr, String pdetails, String pblock, Integer Ppower, Integer preadnum, List<Reply> Replys, List<Users> likedUsers) {
        this.pid = pid;
        this.user = user;
        this.ptitle = ptitle;
        this.pabstr = pabstr;
        this.pdetails = pdetails;
        this.pblock = pblock;
        this.Ppower = Ppower;
        this.preadnum = preadnum;
        this.Replys = Replys;
        this.likedUsers = likedUsers;
    }

    public Date getPdate() {
        return pdate;
    }

    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }


    public int getPid() {
        return this.pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    public String getPtitle() {
        return this.ptitle;
    }

    public void setPtitle(String ptitle) {
        this.ptitle = ptitle;
    }

    public String getPabstr() {
        return this.pabstr;
    }

    public void setPabstr(String pabstr) {
        this.pabstr = pabstr;
    }

    public String getPdetails() {
        return this.pdetails;
    }

    public void setPdetails(String pdetails) {
        this.pdetails = pdetails;
    }

    public String getPblock() {
        return this.pblock;
    }

    public void setPblock(String pblock) {
        this.pblock = pblock;
    }

    public Integer getPreadnum() {
        return this.preadnum;
    }

    public void setPreadnum(Integer preadnum) {
        this.preadnum = preadnum;
    }
    
    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    public Integer getPpower() {
        return Ppower;
    }

    public void setPpower(Integer Ppower) {
        this.Ppower = Ppower;
    }

    public List<Reply> getReplys() {
        return Replys;
    }

    public void setReplys(List<Reply> Replys) {
        this.Replys = Replys;
    }

    public List<Users> getLikedUsers() {
        return likedUsers;
    }

    public void setLikedUsers(List<Users> likedUsers) {
        this.likedUsers = likedUsers;
    }

}
