package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.GenericGenerator;

/**
 * Reply generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "Reply",
        schema = "dbo",
        catalog = "Russh"
)
public class Reply implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "generator", strategy = "native")
    @GeneratedValue(generator = "generator")
    @Column(name = "Rid", unique = true, nullable = false)
    private int rid;
    @JoinColumn(name = "Rpid")
    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.REMOVE)
    private Post post;
    @JoinColumn(name = "Ruid",unique = false)
    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.REMOVE)
    private Users ruser;
    @Column(name = "Rcontent", nullable = false)
    private String rcontent;
    @Column(name = "Rpower", columnDefinition = "int default 0")
    private Integer Rpower;
    @Column(name = "Rtime")
    @Temporal(TemporalType.TIMESTAMP)
    @Generated(GenerationTime.INSERT)
    private Date rtime;

    public Reply() {
    }


    public Reply(Post post, Users user, String rcontent) {
        this.post = post;
        this.ruser = user;
        this.rcontent = rcontent;
    }


    public Users getRuser() {
        return ruser;
    }

    public void setRuser(Users ruser) {
        this.ruser = ruser;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    public Users getUser() {
        return ruser;
    }

    public void setUser(Users user) {
        this.ruser = user;
    }

    public int getRid() {
        return this.rid;
    }

    public void setRid(int rid) {
        this.rid = rid;
    }

    public Integer getRpower() {
        return Rpower;
    }

    public void setRpower(Integer Rpower) {
        this.Rpower = Rpower;
    }

    public String getRcontent() {
        return this.rcontent;
    }

    public void setRcontent(String rcontent) {
        this.rcontent = rcontent;
    }

    public Date getRtime() {
        return this.rtime;
    }

    public void setRtime(Date rtime) {
        this.rtime = rtime;
    }

}
