package com.qdu.pojo;
// Generated 2019-12-10 22:48:34 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;

/**
 * Reply generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name="Reply"
    ,schema="dbo"
    ,catalog="Russh"
)
public class Reply  implements java.io.Serializable {


@Id
    @Column(name="Rid", unique=true, nullable=false)
     private String rid;
     @JoinColumn(name="Rpid", nullable=false)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
     private Post post;
     @JoinColumn(name = "Ruid", nullable = false)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
     private Users users;
     @Column(name="Rcontent", nullable=false)
     private String rcontent;
     @Column(name = "Rpower",columnDefinition = "int default 0")
    private Integer Rpower;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="Rtime", nullable=false, length=23)
     private Date rtime;

    public Reply() {
    }

    public Reply(String rid, Post post, Users users, String rcontent, Date rtime) {
       this.rid = rid;
       this.post = post;
       this.users = users;
       this.rcontent = rcontent;
       this.rtime = rtime;
    }
   
    public String getRid() {
        return this.rid;
    }
    
    public void setRid(String rid) {
        this.rid = rid;
    }

    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    public String getRcontent() {
        return this.rcontent;
    }
    
    public void setRcontent(String rcontent) {
        this.rcontent = rcontent;
    }

    public Date getRtime() {
        return this.rtime;
    }
    
    public void setRtime(Date rtime) {
        this.rtime = rtime;
    }




}


